context:
  version: "0.1.2"

package:
  name: newuoa-cpp
  version: ${{ version }}

source:
  url: https://github.com/elsid/newuoa-cpp/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 660274f2ab2188bdf096c0ed0eefa8e10fe563e440064bc4e48ce547a8ef90a4
  patches:
    - fix_dll_install.patch

build:
  number: 1
  script:
    interpreter: brush
    content: |
      cmake -S . -B build ${CMAKE_ARGS} -DBUILD_SHARED_LIBS=ON
      cmake --build build --parallel ${CPU_COUNT}
      cmake --install build

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - ${{ "make" if unix }}
    - brush
    - cmake
    - pkg-config
  run_exports:
    - ${{ pin_subpackage("newuoa-cpp", upper_bound="x.x") }}

tests:
  - package_contents:
      include:
        - newuoa.h
      lib:
        - newuoa
    strict:
      true

about:
  homepage: https://github.com/elsid/newuoa-cpp
  repository: https://github.com/elsid/newuoa-cpp
  license: MIT
  license_file: LICENSE
  summary: "C++ implementation of NEWUOA algorithm with C interface"

extra:
  recipe-maintainers:
    - eunos-1128
